version: '3.7'

services:

  figstudios-postgres-local:
    restart: always
    image: postgres
    env_file:
      - .env
    volumes:
      - ./docker/local/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  figstudios-be:
    restart: always
    image: figx7/figstudios-be
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 3000:3000


  