version: '3.7'

services:

 
  figstudios-be:
    restart: always
    image: figx7/figstudios-be
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 3000:3000
